First stage of type checking completed successfully with 0 warnings

While type checking, exception was thrown :

line 2 :
  len a

Unexpected argument type, list was expected, int found.
